server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-connections: 20000
    accept-count: 1000
    threads:
      max: 1000
      min-spare: 30

spring:
  application:
    name: demo
  messages:
    basename: i18n/messages
  aop:
    proxy-target-class: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization.write-dates-as-timestamps: false

cors:
  enable: true
  path-pattern: /**
  allow-headers:
  allow-methods: HEAD, GET, POST, PUT, DELETE, OPTIONS
  allow-origin-patterns:
  allow-credentials: true
  max-age: 1800

docket:
  enable: true
  title: Api Document
  description: Project Description
  version: 1.0.1
  license: Apache License, Version 2.0
  contact:
    name: 作者名
    url: http://localhost:8080
    email: 邮箱
  token:
    name: access-token
    description: Access Token
    example: Default Example
